
inicio
    
    inteiro A, B, C
    inteiro quadradoA, quadradoB, quadradoC
    inteiro soma_quadrados


    Escrever "Indique o valor de A: "
    Ler A

    Escrever "Indique o valor de B: "
    Ler B

    Escrever "Indique o valor de C: "
    Ler C

    quadradoA <- A * A
    quadradoB <- B * B
    quadradoC <- C * C

    soma_quadrados <- quadradoA + quadradoB + quadradoC

    Escrever "A soma dos quadrados é: ", soma_quadrados
    
fim
